services:
  postgres:
    image: postgres:16
    container_name: coinly-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: coinly
      POSTGRES_USER: coinly
      POSTGRES_PASSWORD: coinly
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: coinly-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: coinly
      RABBITMQ_DEFAULT_PASS: coinly
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro

  mailpit:
    image: axllent/mailpit:latest
    container_name: coinly-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres-data:
  rabbitmq-data:
