spring:
  application:
    name: coinly-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coinly}
    username: ${DB_USERNAME:coinly}
    password: ${DB_PASSWORD:coinly}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

coinly:
  mail:
    from: noreply@coinly.local

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
